apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-secret
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    volumeMounts:
    - mountPath: /etc/secret
      name: nginx-secret
  volumes:
  - name: nginx-secret
    secret:
      secretName: filename-secret
      defaultMode: 0400
