apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-init
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    volumeMounts:
      - mountPath: /opt/data/
        name: shared-path
  initContainers:
    - name: busybox
      image: busybox:latest
      volumeMounts:
      - mountPath: /tmp/data/
        name: shared-path
      - mountPath: /etc/config
        name: nginx-cm
      command:
        - '/bin/sh'
        - '-c'
        - 'cat /etc/config/namefile.txt & cp /etc/config/namefile.txt /tmp/data/'
  volumes:
  - name: nginx-cm
    configMap:
      name: namefile
  - name: shared-path
    emptyDir: {}
