apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - sevices
  verbs: ['*']
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - create
  - update